site_name: Hackerspace Nijmegen Wiki
docs_dir: docs
site_description: Wiki For The Hackerspace Nijmegen
copyright: 2018 (c) Hackerspace Nijmegen, CC-By-Sa 3.5
theme: alabaster
dev_addr: '127.0.0.1:9000'
theme_dir: custom_theme
site_dir: /var/www/wiki
markdown_extensions:
  - wikilinks
  - codehilite
  - toc(permalink=true)
extra:
  logo: img/logo.jpg
  logo_name: "hackerspace nijmegen"
  include_toc: yes
  extra_nav_links:
     Github: https://github.com/hackerspace-nijmegen
     Twitter: https://twitter.com/Hackerspace024
     Opening hours: https://ethercalc.org/asl9nerzfima

pages:
  - Home: 'index.md'
  - Contact: 'contact.md'
  - About: 'about.md'
  - Contributing: 'contributing.md'
  - Budgets: 'budgets.md'
  - 'Stichting Hackerspace Nijmegen':
    - Statuten: 'statuten.md'
    - Minutes:
      - '2018-03-20': 'minutes/2018-1.md'
      - '2018-03-27': 'minutes/2018-2.md'
  - 'Elzenstraat 4a':
    - CFP: 'callforparticipation.md'
    - Wishlist: 'wishlist.md'
    - 'Space Opening': 'spaceopening.md'
    - 'Looking For A Name': 'naming.md'
  - Projects:
    - 'Knitting Machine to laptop': 'projects/knittingmachine.md'
    - 'Digital entrance': 'projects/digitallocks.md'
  - Events:
    - '2018/06/02 Opening party \o/': 'openingparty.md'
    - '2018/05/04 - Getting started with Ultimaker': 'events/workshops/3dprintergettingstarted.md'
    - '2018/04/22 - Open day': 'events/openday2018.md'
